#!/usr/bin/env python3
"""P55 Phase 2 Stage 6 replay -- one-off utility (not wired into any make
target). Executes the 8-operation replay list scripts/_p55_stage6_prep.py
already generated and verified (prompts/P55-scoped-unblock.md §12.3/§12.9),
ONE OPERATION AT A TIME, comparing each operation's REAL, resulting job_run
row against the ORIGINAL job_run row's own rows_in/rows_out -- printed as a
predicted ledger BEFORE anything runs, per the owner's own instruction
(2026-08-23): "turn one exact bar into eight."

STOPS IMMEDIATELY on the first operation whose actual rows_in/rows_out
differ from predicted -- does not continue to reconcile a global total
afterward. A miss localized to one operation is diagnosable; a global delta
of unknown origin is not (the owner's own words, verbatim, are the argument
for this shape).

No origin fetch anywhere in this file: every operation below is
`ingest_parcels.py --phase e` or `ingest_zoning_permits.py --phase load`,
both bound exclusively to `verified_snapshot_file()` (reads snapshot.
object_uri -- s3://ledgex-snapshots-locked/..., never a San Jose endpoint).
Confirmed by reading phase_e()/phase_zoning_load()/phase_permits_load()
directly before writing this file.

Usage: DATABASE_URL=<fresh, post-rename, post-migrate, post-seed,
post-_p55_stage6_prep.py-register ledgex_schema_check> \
  .venv-ingest/bin/python3 scripts/_p55_stage6_replay.py
"""
import os
import subprocess
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)

from infra.env import get_db  # noqa: E402

# The predicted ledger, mechanically generated by scripts/_p55_stage6_prep.py
# against the SOURCE database (2026-08-23) and reproduced here literally --
# NOT retyped from prose. Each entry: (job_key, snapshot_id, predicted_rows_in,
# predicted_rows_out, argv for the real ingest call).
PARCELS_SID_A = "ca_san_jose.parcels:sha256:0216d539a3995ccc88e4b6542ad8aa936fb6078e74ea39402444a96c5b172fe2"
PARCELS_SID_B = "ca_san_jose.parcels:sha256:b98138f01644b1b58c7161582c8f01ee2107e63eb6ce157737cea280c9655ce0"
ZONING_SID = "ca_san_jose.zoning_districts:sha256:699ec193384d4894d68d04b91df2f2531c4587e65488de560087be925adf451b"
ZONING_SID_A = "ca_san_jose.zoning_districts:sha256:eae7823a22e72537d5738d473c6c8289e0e2af78e76be782ea5e432fdd5d04ba"
PERMITS_SID = "ca_san_jose.building_permits_active:sha256:70bf19c13dadebe65321d0d56efce66ded036f0022be1dcef7972330c7c72640"
PERMITS_SID_A = "ca_san_jose.building_permits_active:sha256:8f3328b5cb9845228bb6bb11aac4a0b33289105a4134d5d2c42af78d2d6afffb"

REPLAY = [
    ("ingest_parcels_full", PARCELS_SID_A, 225039, 225039,
     [sys.executable, "scripts/ingest_parcels.py", "--phase", "e", "--snapshot-id", PARCELS_SID_A]),
    ("ingest_zoning", ZONING_SID_A, 225042, 214892,
     [sys.executable, "scripts/ingest_zoning_permits.py", "--source", "zoning", "--phase", "load",
      "--snapshot-id", ZONING_SID_A]),
    ("ingest_permits", PERMITS_SID_A, 17499, 8322,
     [sys.executable, "scripts/ingest_zoning_permits.py", "--source", "permits", "--phase", "load",
      "--snapshot-id", PERMITS_SID_A]),
    ("ingest_parcels_full", PARCELS_SID_B, 25, 25,
     [sys.executable, "scripts/ingest_parcels.py", "--phase", "e", "--snapshot-id", PARCELS_SID_B]),
    ("ingest_zoning", ZONING_SID, 225088, 522,
     [sys.executable, "scripts/ingest_zoning_permits.py", "--source", "zoning", "--phase", "load",
      "--snapshot-id", ZONING_SID]),
    ("ingest_permits", PERMITS_SID, 2, 0,
     [sys.executable, "scripts/ingest_zoning_permits.py", "--source", "permits", "--phase", "load",
      "--snapshot-id", PERMITS_SID]),
    ("ingest_zoning", ZONING_SID, 225088, 443,
     [sys.executable, "scripts/ingest_zoning_permits.py", "--source", "zoning", "--phase", "load",
      "--snapshot-id", ZONING_SID]),
    ("ingest_permits", PERMITS_SID, 3, 0,
     [sys.executable, "scripts/ingest_zoning_permits.py", "--source", "permits", "--phase", "load",
      "--snapshot-id", PERMITS_SID]),
]


def latest_job_run_since(conn, job_key, snapshot_id, since_ts):
    """The one new job_run row this operation just wrote -- started_at >
    since_ts disambiguates a re-run of the identical (job_key, snapshot_id)
    pair (zoning/permits, each run twice) from the earlier row with the
    same key."""
    with conn.cursor() as cur:
        cur.execute(
            "SELECT id, status, rows_in, rows_out, started_at FROM job_run "
            "WHERE job_key = %s AND snapshot_id = %s AND started_at > %s "
            "ORDER BY started_at DESC LIMIT 1",
            (job_key, snapshot_id, since_ts),
        )
        return cur.fetchone()


def main():
    print("=" * 78)
    print("PREDICTED LEDGER (from scripts/_p55_stage6_prep.py's own mechanical "
          "generation, prompts/P55-scoped-unblock.md §12.3/§12.9)")
    print("=" * 78)
    for i, (job_key, sid, pin, pout, _argv) in enumerate(REPLAY, start=1):
        print(f"  [{i}] {job_key:22s} rows_in={pin:>7} rows_out={pout:>7}  {sid}")
    print()

    conn = get_db()
    with conn.cursor() as cur:
        cur.execute("SELECT now()")
        start_ts = cur.fetchone()[0]
    conn.rollback()

    for i, (job_key, sid, predicted_in, predicted_out, argv) in enumerate(REPLAY, start=1):
        print("=" * 78)
        print(f"[{i}/8] RUNNING: {' '.join(argv)}")
        print("=" * 78)
        with conn.cursor() as cur:
            cur.execute("SELECT now()")
            before_ts = cur.fetchone()[0]
        conn.rollback()

        result = subprocess.run(argv, cwd=REPO_ROOT)
        if result.returncode != 0:
            print(f"\nSTOP: operation [{i}] exited {result.returncode}. "
                  f"Not continuing to operation [{i+1}].")
            sys.exit(1)

        row = latest_job_run_since(conn, job_key, sid, before_ts)
        conn.rollback()
        if row is None:
            print(f"\nSTOP: operation [{i}] produced no new job_run row for "
                  f"({job_key!r}, {sid!r}) after {before_ts}. Cannot verify.")
            sys.exit(1)
        _id, status, actual_in, actual_out, started_at = row

        match = (status == "succeeded" and actual_in == predicted_in and actual_out == predicted_out)
        print(f"  predicted: rows_in={predicted_in} rows_out={predicted_out}")
        print(f"  actual:    rows_in={actual_in} rows_out={actual_out} status={status}")
        if match:
            print(f"  [{i}/8] MATCH")
        else:
            print(f"\nSTOP: operation [{i}] DEVIATED from prediction. "
                  f"delta rows_in={actual_in - predicted_in if actual_in is not None else '?'} "
                  f"rows_out={actual_out - predicted_out if actual_out is not None else '?'}. "
                  f"Not continuing to operation [{i+1}] -- localize and diagnose this one "
                  f"before proceeding, per the owner's own instruction.")
            sys.exit(1)
        print()

    print("=" * 78)
    print("ALL 8 OPERATIONS MATCHED PREDICTION EXACTLY.")
    print("=" * 78)


if __name__ == "__main__":
    main()
