#!/usr/bin/env python3
"""P52 -- proof that the rights-vs-diligence REPORTING split (api/main.py's
derive_rights_position/derive_diligence, GET /v1/rights, and
GET /v1/parcels/{id}/facts' omitted_for_rights) does what Phase 1's plan
and Phase 2's four amendments require, and nothing more.

Two kinds of check here, mirroring scripts/test_viewer_rights_gate.py's own
split between "call the pure function" and "call the real route against a
real database":

  1. PURE, no database: the full derive_rights_position truth table (every
     commercial_use x redistribution x restriction combination -- all 45,
     not a sample) and the three-state derive_diligence table. Each
     expected value below is hand-written independently of api/main.py's
     implementation, transcribed directly from Amendment 1/2's own
     precedence rules -- not generated by calling the function under test
     and asserting it agrees with itself.

  2. DATABASE-BACKED, against real seeded data (db/seeds/day4_sources.sql):
     the model_training-rationale-distinctness requirement (P52 prompt
     section 3), the no-fabrication requirement (section 6), and a
     default-deny-is-reporting-blind check directly against
     core.rights.evaluate_rights_gate using a fake cursor -- proving this
     pass did not touch that function's behavior, not merely asserting it
     by inspection.

Run: DATABASE_URL=... .venv-api/bin/python3 scripts/test_rights_reporting.py
(same DATABASE_URL contract as scripts/test_viewer_rights_gate.py -- this
script does not seed anything itself and does not require the P42 fixture;
it reads cc0/cc_by_4_0 directly, which db/seeds/day4_sources.sql already
provides on any database it has been applied to.)

Read-only. Writes nothing.
"""
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)

from infra.env import get_db  # noqa: E402
from core.rights import evaluate_rights_gate  # noqa: E402
import api.main as viewer  # noqa: E402

failures = []


def check(label, condition, detail=""):
    status = "PASS" if condition else "FAIL"
    print(f"[{status}] {label}" + (f" -- {detail}" if detail and not condition else ""))
    if not condition:
        failures.append(label)


# ---------------------------------------------------------------------------
# 1a. derive_rights_position -- the full 45-row truth table
# ---------------------------------------------------------------------------
# permission_state (0001): 'allowed', 'prohibited', 'unknown'.
# use_restriction (0001):  'open', 'attribution', 'noncommercial',
#                          'no_resale', 'unknown'.
PERMISSION_STATES = ("allowed", "prohibited", "unknown")
RESTRICTIONS = ("open", "attribution", "noncommercial", "no_resale", "unknown")

RIGHTS_POSITION_TABLE = {}
for cu in PERMISSION_STATES:
    for rd in PERMISSION_STATES:
        for rs in RESTRICTIONS:
            if cu == "unknown" or rd == "unknown" or rs == "unknown":
                expected = "unknown"
            elif cu == "prohibited" or rd == "prohibited":
                expected = "prohibits_use"
            elif rs == "open":
                expected = "permits_use"
            else:
                expected = "permits_with_conditions"
            RIGHTS_POSITION_TABLE[(cu, rd, rs)] = expected

# Spot-check the table itself against the two real seeded licences and the
# one real prohibited example this repo declares (sanborn_asserted,
# jurisdictions/ca_san_jose/sources.yaml/licences.yaml -- not seeded as a
# real licence row, but its combination is a real, named one) -- catches a
# transcription error in the 45-row generation above before trusting it to
# grade api/main.py.
assert RIGHTS_POSITION_TABLE[("allowed", "allowed", "open")] == "permits_use"
assert RIGHTS_POSITION_TABLE[("allowed", "allowed", "attribution")] == "permits_with_conditions"
assert RIGHTS_POSITION_TABLE[("prohibited", "prohibited", "noncommercial")] == "prohibits_use"
assert RIGHTS_POSITION_TABLE[("unknown", "unknown", "unknown")] == "unknown"
assert len(RIGHTS_POSITION_TABLE) == 45


def test_rights_position_matrix():
    for (cu, rd, rs), expected in sorted(RIGHTS_POSITION_TABLE.items()):
        got = viewer.derive_rights_position(cu, rd, rs)
        check(
            f"derive_rights_position(commercial_use={cu!r}, redistribution={rd!r}, "
            f"restriction={rs!r}) == {expected!r}",
            got == expected,
            f"got {got!r}",
        )
    # Amendment 1's own forbidden values -- never emitted for any input.
    forbidden = {"allowed", "restricted"}
    emitted = set(RIGHTS_POSITION_TABLE.values())
    check(
        "no forbidden rights_position value ('allowed', 'restricted') is ever emitted",
        emitted.isdisjoint(forbidden),
        f"emitted values: {sorted(emitted)}",
    )


# ---------------------------------------------------------------------------
# 1b. derive_diligence -- the three-state table (Amendment 2)
# ---------------------------------------------------------------------------
DILIGENCE_TABLE = {
    # (cleared_by, evidence_uri) -> expected
    (None, None): "written_confirmation_pending",
    (None, "s3://evidence/whatever"): "written_confirmation_pending",  # cleared_by NULL wins
    ("someone", None): "cleared_unevidenced",
    ("someone", "s3://evidence/whatever"): "cleared",
}


def test_diligence_matrix():
    for (cleared_by, evidence_uri), expected in DILIGENCE_TABLE.items():
        got = viewer.derive_diligence(cleared_by, evidence_uri)
        check(
            f"derive_diligence(cleared_by={cleared_by!r}, evidence_uri={evidence_uri!r}) == {expected!r}",
            got == expected,
            f"got {got!r}",
        )
    # Amendment 2's whole point: a cleared_by with no evidence_uri must NOT
    # read as plain "cleared" -- the exact shape of the closed CLAUDE.md
    # contamination incident (fabricated cleared_by='test', no evidence).
    check(
        "cleared_by set + evidence_uri NULL is 'cleared_unevidenced', never plain 'cleared'",
        viewer.derive_diligence("someone", None) == "cleared_unevidenced",
    )


# ---------------------------------------------------------------------------
# 2a. core.rights.evaluate_rights_gate -- untouched, proven with a fake
#     cursor rather than asserted by inspection. Also covers section 6's
#     "a licence with no licence_channel row at all still reports as
#     blocked" -- default-deny is evaluate_rights_gate's own behavior,
#     reporting cannot see or change it.
# ---------------------------------------------------------------------------
class _FakeCursor:
    """Returns zero licence_channel rows for every licence_id, simulating a
    real licence that has a `licence` row (satisfying fact.licence_id's FK)
    but literally no licence_channel row for any channel -- the case
    default-deny (0002) exists for. No real database involved; this is
    exactly what evaluate_rights_gate's own SELECT would see against such a
    licence."""

    def execute(self, query, params):
        self._params = params

    def fetchall(self):
        return []  # zero licence_channel rows found, for any licence_id queried


def test_default_deny_unaffected_by_reporting():
    touched = [
        ("fact-1", "some.field", "licence_with_no_channel_rows", "some value"),
    ]
    allowed_by_licence, blocked_by_licence = evaluate_rights_gate(
        _FakeCursor(), touched, "api"
    )
    check(
        "a licence with zero licence_channel rows is absent from allowed_by_licence "
        "(not merely False) -- .get(id, False) is still the only safe read",
        "licence_with_no_channel_rows" not in allowed_by_licence,
    )
    check(
        "that licence's touched field is blocked (default-deny), unchanged by this pass",
        blocked_by_licence.get("licence_with_no_channel_rows") == ["some.field"],
        f"got {blocked_by_licence}",
    )


# ---------------------------------------------------------------------------
# 2b/2c. Against real seeded data (db/seeds/day4_sources.sql)
# ---------------------------------------------------------------------------
def test_model_training_rationale_distinct_from_the_other_five():
    """P52 prompt section 3, THE TRAP: rights_position/diligence are
    licence-level; the reason a specific CHANNEL is blocked is
    channel-level, and licence_channel.rationale must stay authoritative
    per channel -- never flattened into one licence-level string. If a
    future refactor collapses per-channel rationale into a single
    licence-level label, cc_by_4_0's model_training row (denied for its
    OWN, independent reason -- 0032, C9) would silently start reporting
    the same reason as free_snapshot/paid_property_file/api/bulk_export/
    analytics. This test exists to catch exactly that regression, not to
    exercise happy-path plumbing."""
    conn = get_db()
    try:
        rows = viewer.get_rights(conn)["data"]
    finally:
        conn.close()

    cc_by_4_0_rows = {r["channel"]: r["rationale"] for r in rows if r["licence_id"] == "cc_by_4_0"}
    check(
        "cc_by_4_0 has all six channels present in GET /v1/rights",
        set(cc_by_4_0_rows) == {
            "free_snapshot", "paid_property_file", "api", "bulk_export",
            "analytics", "model_training",
        },
        f"got channels: {sorted(cc_by_4_0_rows)}",
    )
    other_five = {ch: r for ch, r in cc_by_4_0_rows.items() if ch != "model_training"}
    check(
        "the other five channels share one identical rationale string",
        len(set(other_five.values())) == 1,
        f"got {len(set(other_five.values()))} distinct rationale strings among the five",
    )
    check(
        "model_training's rationale is NOT the same string as the other five",
        cc_by_4_0_rows.get("model_training") not in set(other_five.values()),
        f"model_training rationale: {cc_by_4_0_rows.get('model_training')!r}",
    )
    check(
        "model_training's rationale explicitly names model-training use, not generic sign-off",
        "model-training" in (cc_by_4_0_rows.get("model_training") or ""),
        f"got: {cc_by_4_0_rows.get('model_training')!r}",
    )
    # rights_position/diligence, being licence-level, ARE the same across
    # all six rows -- confirming they are context, not a per-channel
    # decision, the distinction section 3 requires the viewer to preserve.
    rights_positions = {r["rights_position"] for r in rows if r["licence_id"] == "cc_by_4_0"}
    diligences = {r["diligence"] for r in rows if r["licence_id"] == "cc_by_4_0"}
    check(
        "rights_position is identical across all six of cc_by_4_0's channel rows (licence-level)",
        len(rights_positions) == 1,
        f"got {rights_positions}",
    )
    check(
        "diligence is identical across all six of cc_by_4_0's channel rows (licence-level)",
        len(diligences) == 1,
        f"got {diligences}",
    )


def test_no_fabricated_evidence_in_either_response():
    """cc0/cc_by_4_0 both carry evidence_uri IS NULL in every reachable
    seeded database (Phase 1 section 3, confirmed again here live) --
    neither GET /v1/rights nor GET /v1/parcels/{id}/facts may report
    diligence='cleared' for either, since 'cleared' asserts a retained
    evidence artifact exists."""
    conn = get_db()
    try:
        rights_rows = viewer.get_rights(conn)["data"]
    finally:
        conn.close()

    for licence_id in ("cc0", "cc_by_4_0"):
        rows = [r for r in rights_rows if r["licence_id"] == licence_id]
        check(
            f"{licence_id}: evidence_uri is NULL in the live database (not this test's assumption)",
            all(r["evidence_uri"] is None for r in rows),
            f"got evidence_uri values: {[r['evidence_uri'] for r in rows]}",
        )
        check(
            f"{licence_id}: diligence is never 'cleared' while evidence_uri is NULL",
            all(r["diligence"] != "cleared" for r in rows),
            f"got diligence values: {[r['diligence'] for r in rows]}",
        )


# P55 Phase 2, §7/T8: additive coverage for the two new scoped-unblock
# licence ids -- NEW functions, not edits to the two above. The existing
# assertions about cc0/cc_by_4_0 stay true and unmodified (both retain their
# original six-channel, model_training-distinct, no-fabrication shape); this
# is parallel coverage for cc_by_4_0_api_2026_08/cc0_api_2026_08, which carry
# the identical shape (design §4.3/§4.4) except one channel (api) is now
# allowed=true rather than false.
P55_NEW_LICENCE_IDS = ("cc_by_4_0_api_2026_08", "cc0_api_2026_08")


def test_model_training_rationale_distinct_new_licence_ids():
    """Same property as test_model_training_rationale_distinct_from_the_other_five,
    for the two P55 licence ids: model_training keeps its own, independent
    rationale, never collapsed into the (now five, still 'the other five'
    minus api which is a different string again) shared text."""
    conn = get_db()
    try:
        rows = viewer.get_rights(conn)["data"]
    finally:
        conn.close()

    for licence_id in P55_NEW_LICENCE_IDS:
        by_channel = {r["channel"]: r["rationale"] for r in rows if r["licence_id"] == licence_id}
        check(
            f"{licence_id} has all six channels present in GET /v1/rights",
            set(by_channel) == {
                "free_snapshot", "paid_property_file", "api", "bulk_export",
                "analytics", "model_training",
            },
            f"got channels: {sorted(by_channel)}",
        )
        check(
            f"{licence_id}: model_training's rationale is distinct from api's",
            by_channel.get("model_training") != by_channel.get("api"),
            f"model_training={by_channel.get('model_training')!r} api={by_channel.get('api')!r}",
        )
        check(
            f"{licence_id}: model_training's rationale explicitly names model-training use",
            "model-training" in (by_channel.get("model_training") or ""),
            f"got: {by_channel.get('model_training')!r}",
        )


def test_no_fabricated_evidence_new_licence_ids():
    """Same property as test_no_fabricated_evidence_in_either_response, for
    the two P55 licence ids -- C1's guard, restated here at the reporting
    layer (T2 in scripts/test_scoped_unblock.py already asserts it directly
    against licence.cleared_by/cleared_at/evidence_uri; this is the same
    fact checked through GET /v1/rights's own derived fields instead)."""
    conn = get_db()
    try:
        rights_rows = viewer.get_rights(conn)["data"]
    finally:
        conn.close()

    for licence_id in P55_NEW_LICENCE_IDS:
        rows = [r for r in rights_rows if r["licence_id"] == licence_id]
        check(
            f"{licence_id}: evidence_uri is NULL in the live database",
            all(r["evidence_uri"] is None for r in rows),
            f"got evidence_uri values: {[r['evidence_uri'] for r in rows]}",
        )
        check(
            f"{licence_id}: diligence is never 'cleared' while evidence_uri is NULL",
            all(r["diligence"] != "cleared" for r in rows),
            f"got diligence values: {[r['diligence'] for r in rows]}",
        )
        check(
            f"{licence_id}: diligence is exactly 'written_confirmation_pending' everywhere",
            all(r["diligence"] == "written_confirmation_pending" for r in rows),
            f"got diligence values: {[r['diligence'] for r in rows]}",
        )


if __name__ == "__main__":
    test_rights_position_matrix()
    test_diligence_matrix()
    test_default_deny_unaffected_by_reporting()
    test_model_training_rationale_distinct_from_the_other_five()
    test_no_fabricated_evidence_in_either_response()
    test_model_training_rationale_distinct_new_licence_ids()
    test_no_fabricated_evidence_new_licence_ids()
    print(f"\n{len(failures)} failure(s)" if failures else "\nAll assertions passed")
    sys.exit(1 if failures else 0)
